# Generated by Django 6.0.6 on 2026-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('ssh_port', models.IntegerField(default=22)),
                ('ssh_user', models.CharField(max_length=50)),
                ('ssh_password', models.CharField(max_length=100)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('api_login', models.CharField(blank=True, max_length=50, null=True)),
                ('api_password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
