# Generated by Django 6.0.6 on 2026-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ssh_auth_type',
            field=models.CharField(choices=[('password', 'Password'), ('key', 'SSH Key')], default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='ssh_private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='server',
            name='updeted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
