# Generated by Django 6.0.6 on 2026-07-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_ssh_auth_type_server_ssh_private_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='updeted_at',
            new_name='updated_at',
        ),
    ]
